Qshop/Buyer/urls.py
#-*- coding:utf-8 -*-
"""
@Time:2020/9/3010:48
@Auth:DaiXvWen
@File:urls.py
"""

# 从Store中导入所有视图
from django.urls import path,include,re_path
from Buyer.views import *

# from rest_framework.routers import DefaultRouter
# from Buyer.serializer import *
# router=DefaultRouter()
# #收集注册路由，注册路由器
# router.register("morelist",MoreListView,basename="")

urlpatterns = [
    path('index/', index),                          #前台页面：首页
    path('login/', login),                          #前台页面：登录界面
    path('register/', register),                    #前台页面：注册界面
    path('cart/', cart),                            #前台页面：购物车
    path('edit_address/', edit_address),            #前台页面：修改地址
    path('edit_user/', edit_user),                  #前台页面：修改用户信息
    path('myorders/', myorders),                    #前台页面：我的订单
    path('usercenterinfo/', usercenterinfo),        #前台页面：个人用户中心页面
    path('list/', list),                            #前台页面：列表页面展示
    re_path('detail/(\w*)/', detail),               #前台页面：商品详情页面
    path('logout/', logout),                        #前台页面：登出路由
    path('place_order/', place_order),              #前台页面：订单结算页面
]

Qshop/Qshop/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from Buyer.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('buyer/',include("Buyer.urls")),
    path('store/',include("Store.urls")),
    re_path("^$",index)     #配置到首页的路由，^$不匹配任何东西



]

Qshop/Buyer/models.py
from Store.models import *
from django.db import models

# Create your models here.

##创建订单表与订单详情表
class PlaceOrder(models.Model):
    """
    订单表，一表
    """
    order_num = models.CharField(max_length=32,verbose_name="订单编号")
    order_status = models.IntegerField(default=0,verbose_name="订单状态")  # 0 代表未支付  1 代表已支付   2 发货中
    type_number = models.IntegerField(default=0,verbose_name="商品数量")
    total_price = models.FloatField(verbose_name="订单总金额")
    # order_address = models.ForeignKey(to=RecvAddress,on_delete=models.CASCADE,verbose_name="收货地址")
    user_id = models.ForeignKey(to=QUser,on_delete=models.CASCADE,verbose_name="买家")
    class Meta:
        db_table="placeorder"


class OrderInfo(models.Model):
    """
    订单详情表，多表
    """
    goods_name = models.CharField(verbose_name="商品名字",max_length=32)
    goods_price = models.FloatField(verbose_name="商品单价")
    goods_num = models.IntegerField(verbose_name="商品数量")
    goods_picture = models.CharField(max_length=64,verbose_name="商品图片")
    goods_total = models.FloatField(verbose_name="商品小计")
    goods_status =models.IntegerField(verbose_name="商品状态")
    store = models.ForeignKey(to=Store,on_delete=models.CASCADE)
    order = models.ForeignKey(to=PlaceOrder,on_delete=models.CASCADE)
    class Meta:
        db_table = "orderinfo"

Qshop/Buyer/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from Store.models import *
from Buyer.models import OrderInfo,PlaceOrder
#json与ajax测试，返回一个json格式的用户信息
from django.http import JsonResponse
# Create your views here.


#密码加密
from Store.views import SetPassword

#登录装饰器
def LoginValid(func):
    def inner(request,*args,**kwargs):
        """
        获取cookie和session的信息:
            cookie:b_name，b_user_id
            session:b_user_id
        """
        cookie_username=request.COOKIES.get("b_name")
        cookie_userid=request.COOKIES.get("b_user_id")
        session_id=request.session.get('b_id')

        #如果cookie和session存在
        if cookie_userid and session_id:

            #针对中文账号登陆问题
            # cooki_username=cooki_username.encode('ISO-8859-1').decode('utf-8')
            """
            查询匹配内容：
                username：用户名
                id：用户id
                usertype：用户类型
            """
            flag=QUser.objects.filter(
                username=cookie_username,
                id=session_id,
                usertype=0
            ).exists()
            if flag:
                return func(request,*args,**kwargs)

        return HttpResponseRedirect('/buyer/login')
    return inner


#注册，用户注册，与后台的用户同用一张用户表
def register(request):
    if request.method=='POST':
        user_name=request.POST.get("user_name")
        user_pwd=request.POST.get("user_pwd")
        user_cpwd=request.POST.get("user_cpwd")
        user_email=request.POST.get("user_email")
        user_allow=request.POST.get("user_allow")

        #判断用户名是否存在，密码是否一致并符合要求，用户协议是否同意
        flag=QUser.objects.filter(username=user_name).exists()
        if not flag:
            if user_pwd==user_cpwd and user_allow=="on":
                QUser.objects.create(
                    username=user_name,
                    password=SetPassword(user_pwd),
                    email=user_email

                )
                return HttpResponseRedirect('/buyer/login')
            else:
                print('校验没通过')
        else:
            print("用户名存在")

    return render(request,'buyer/register.html',locals())


#登录，购物用户登录
def login(request):

    if request.method=='POST':
        user_name=request.POST.get('user_name')
        user_pwd=request.POST.get('user_pwd')

        flag = QUser.objects.filter(
            username=user_name, password=SetPassword(user_pwd), usertype=0).exists()
        user_id = QUser.objects.filter(username=user_name).first().id
        if flag:

            # 校验成功重定向到index界面
            response = HttpResponseRedirect("/buyer/index")

            """
            下发cookie和session:
                cookie:name，user_id
                session:user_id
            """
            response.set_cookie("b_name", user_name, expires=259200)
            response.set_cookie("b_user_id", user_id, expires=259200)
            request.session["b_id"] = user_id

            return response
        else:
            print("账号密码不正确")



    return render(request,'buyer/login.html',locals())


#登出视图
def logout(request):
    # 删除
    resp = HttpResponseRedirect("/buyer/index/")
    resp.delete_cookie("b_name")
    resp.delete_cookie("b_user_id")
    del request.session["b_id"]
    return resp

#缓存
from django.views.decorators.cache import cache_page
#首页
# @cache_page(3*60)    #设置3分钟的缓存
def index(request):

    goods_list_bh3=Goods.objects.filter(g_type_id=5).all()[:5]   #goods为崩坏系列

    goods_list_sq=Goods.objects.filter(g_type_id=4).all()[:5]   #goods为少前系列

    goods_list_ark=Goods.objects.filter(g_type_id=1).all()[:5]    #明日方舟

    goods_list_gi=Goods.objects.filter(g_type_id=2).all()[:5]    #原神


    goods_list_azur=Goods.objects.filter(g_type_id=3).all()[:5]   #碧蓝航线

    goods_list_pcr=Goods.objects.filter(g_type_id=6).all()[:5]     #公主连结


    return render(request,'buyer/index.html',locals())

#购物车
@LoginValid
def cart(request):
    goods_id = request.GET.get("id")  # 商品id
    goods_count = request.GET.get("count")  # 商品数量
    userid = request.session.get("b_id")
    print(goods_id)
    print(goods_count)
    print(userid)
    return render(request,'buyer/cart.html',locals())


##修改购物地址
@LoginValid
def edit_address(request):

    return render(request,'buyer/edit-address.html',locals())

##修改用户信息
@LoginValid
def edit_user(request):

    return render(request,'buyer/edit-user.html',locals())


##我的订单
@LoginValid
def myorders(request):

    return render(request,'buyer/myorders.html',locals())

#detail界面立刻购买生成订单
import time
@LoginValid
def place_order(request):
    goods_id=request.GET.get("id")        #商品id
    goods_count=request.GET.get("count")  #商品数量
    userid=request.session.get("b_id")

    goods=Goods.objects.filter(id=int(goods_id)).first()
    #先生成placeorder的信息
    porder=PlaceOrder()
    porder.order_num = str(time.time()).replace(".","")    #用time.time作为订单编号
    porder.type_number =int(goods_count)
    porder.total_price =goods.g_price*int(goods_count)
    porder.user_id_id =userid
    porder.save()

    #再生成orderinfo的信息
    orderinfo=OrderInfo()
    orderinfo.goods_name = goods.g_name
    orderinfo.goods_price = goods.g_price
    orderinfo.goods_num = int(goods_count)
    orderinfo.goods_picture = goods.g_picture
    orderinfo.goods_total = goods.g_price*int(goods_count)
    orderinfo.goods_status = 0
    orderinfo.store = goods.g_store
    orderinfo.order = porder
    orderinfo.save()
    return render(request,"buyer/place_order.html",locals())

#用户中心个人信息
@LoginValid
def usercenterinfo(request):

    return render(request,'buyer/user-center-info.html',locals())


#list界面
@LoginValid
# @cache_page(3*60)    #设置3分钟的缓存
def list(request):

    # 新品推荐商品
    goods_new = Goods.objects.all()[::-1][:2]

    return render(request,'buyer/list.html',locals())

#detail界面，商品详细信息
@LoginValid
def detail(request,goods_id):
    # print(goods_id)  #119
    #传入商品的id
    goods_detail=Goods.objects.filter(id=goods_id).first()

    #新品推荐商品
    goods_new=Goods.objects.all()[::-1][:2]

    return render(request,'buyer/detail.html',locals())

Qshop/Buyer/templates/buyer/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            
        {% endblock %}
    </title>


    <script src="/static/buyer/js/jquery.min.js"></script>
    <link rel="stylesheet" href="/static/buyer/css/bootstrap.css"/>
    <script src="/static/buyer/js/bootstrap.js"></script>
    <link rel="stylesheet" href="/static/buyer/css/footer.css">
    <link rel="shortcut icon" href="/static/buyer/images/雪花图标_蓝.ico" >

    {% block script %}

    <link rel="stylesheet" href="/static/buyer/css/index.css">

    {% endblock %}

    {% block style %}{% endblock %}
    
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container-fluid container">
        <div class="navbar-header ">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/buyer/index">欢迎来到天天生鲜</a>
        </div>
        <!-- 所有的登陆注销项导航栏类目 -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                {% if request.COOKIES.b_name %}
                    <li><a href="#">{{request.COOKIES.b_name}}</a></li>
                    <li><a href="/buyer/logout">退出</a></li>
                {% else %}
                    <li><a href="/buyer/login">登录</a></li>
                    <li><a href="/buyer/register">注册</a></li>
                {% endif %}
                <li><a href="/buyer/usercenterinfo">用户中心</a></li>
                <li><a href="/buyer/cart">我的购物车</a></li>
                <li><a href="/buyer/myorders">我的订单</a></li>

            </ul>
        </div>
    </div>
</nav>

{% block content %}
{% endblock %}

<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>
{% block js %}
{% endblock %}

</body>
</html>

Qshop/Buyer/templates/buyer/cart.html
{% extends 'buyer/base.html' %}

{% block title %}
    购物车
{% endblock %}




{% block script %}
   <link rel="stylesheet" href="/static/buyer/css/cart.css">
    <link rel="stylesheet" href="/static/buyer/css/search.css">
{% endblock %}

{% block content %}
<div class="container">

    <!--2.搜索框开始-->
    <div class="search col-sm-12">
        <div class="row">
            <!--左边图片和文字-->
            <div class="col-lg-5">
                <img src="/static/buyer/images/logo.png" alt="..." class="img-rounded">
                <span>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;购物车</span>
            </div>
            <!--右边表单-->
            <div class="col-lg-6 col-lg-offset-1 search_bar">
                <form action="">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="搜索商品">
                        <span class="input-group-btn">
                    <button class="btn btn-success" style="padding: 6px 50px" type="submit">搜索</button>
                </span>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-sm-12">
        <table class="table row">
            <caption>全部商品<span class="text-danger total_count">2</span>件</caption>
            <thead>
            <tr>
                <td class="col-lg-1"></td>
                <td class="col-lg-2">商品名称</td>
                <td class="col-lg-2">商品单位</td>
                <td class="col-lg-2">商品价格</td>
                <td class="col-lg-2">数量</td>
                <td class="col-lg-2">小计</td>
                <td class="col-lg-1">操作</td>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td><input type="checkbox"></td>
                <td>
                    <span class="center-block">奇异果</span>
                    <img src="/static/buyer/images/goods/goods012.jpg" class="width_100 height_100 border_1">
                </td>
                <td>500g</td>
                <td>25.80元</td>
                <td>
                    <div class="input-group width_100">
                    <span class="input-group-btn">
                        <button class="btn btn-default add" type="button">+</button>
                    </span>
                        <input type="text" class="form-control text-center count" name="search" value="1"
                               style="width: 50px">
                        <span class="input-group-btn">
                        <button class="btn btn-default minus" type="button">-</button>
                    </span>
                    </div>
                </td>
                <td>25.80元</td>
                <td>
                    <a href="#">删除</a>
                </td>
            </tr>
            <tr>
                <td><input type="checkbox"></td>
                <td>
                    <span class="center-block">橘子</span>
                    <img src="/static/buyer/images/goods/goods013.jpg" class="width_100 height_100 border_1">
                </td>
                <td>500g</td>
                <td>12.50元</td>
                <td>
                    <div class="input-group width_100">
                    <span class="input-group-btn">
                        <button class="btn btn-default add" type="button">+</button>
                    </span>
                        <input type="text" class="form-control text-center count" name="search" value="5"
                               style="width: 50px">
                        <span class="input-group-btn">
                        <button class="btn btn-default minus" type="button">-</button>
                    </span>
                    </div>
                </td>
                <td>62.50元</td>
                <td>
                    <a href="#">删除</a>
                </td>
            </tr>
            </tbody>
            <tfoot>
            <tr>
                <td><input type="checkbox"></td>
                <td>全选</td>
                <td colspan="4" class="text-right">
                    <span class="center-block">合计(不含运费)：¥<span class="text-danger total_price">42.6</span></span>
                    <span class="center-block">共计<span class="text-danger total_count">2</span>件商品</span>
                </td>
                <td>
                    <a href="/buyer/place_order" class="btn btn-danger">去结算</a>
                </td>
            </tr>
            </tfoot>
        </table>
    </div>

</div>
{% endblock %}

{% block js %}

    <script type="text/javascript">
    /*计算被选中的商品的总件数和总价格*/
    function update_page_info() {
        // 获取所有被选中的商品的checkbox
        // 获取所有被选中的商品所在的ul元素
        total_count = 0;
        total_price = 0;
        $("tbody").find(":checked").parents("tr").each(function () {
            // 获取商品的数目和小计
            count = $(this).children("td").eq(4).find("input").val()
            amount = $(this).children("td").eq(5).text()
            // 累加计算商品的总件数和总价格
            count = parseInt(count)
            amount = parseFloat(amount)
            total_count += count
            total_price += amount
        })
        // 设置被选中的商品的总件数和总价格
        $(".total_price").text(total_price.toFixed(2))
        $(".total_count").text(total_count)
    }

    /*商品的全选和全不选*/
    $("tfoot").find(":checkbox").change(function () {
        // 获取全选的checkbox的选中状态
        is_checked = $(this).prop("checked")
        // 遍历商品的对应的checkbox，设置这些checkbox的选中状态和全选的checkbox保持一致
        $("tbody").find(":checkbox").each(function () {
            $(this).prop("checked", is_checked)
        })
        // 更新页面的信息
        update_page_info()
    })

    /*商品对应的checkbox状态发生改变时，设置全选checkbox的状态*/
    $("tbody").find(":checkbox").change(function () {
        // 获取页面上所有商品的数目
        all_len = $("tbody").children("tr").length
        // 获取页面上被选中的商品的数目
        checked_len = $("tbody").find(":checked").length
        is_checked = true
        if (checked_len < all_len) {
            is_checked = false
        }
        $("tfoot").find(":checkbox").prop("checked", is_checked)
        // 更新页面的信息
        update_page_info()
    })
    /*购物车商品数量的增加*/
    $(".add").click(function () {
        // 获取商品的单价和商品的数量
        price = parseFloat($(this).parents("td").prev().text())
        count = parseInt($(this).parent().next().val())
        //计算
        count++
        // 重新计算商品的数目
        $(this).parent().next().val(count)
        //重新计算商品小计
        amount = count * price
        $(this).parents("td").next().text(amount.toFixed(2) + "元")
        // 获取商品对应的checkbox的选中状态，如果被选中，更新页面信息
        is_checked = $(this).parents("tr").find(":checkbox").prop("checked")
        if (is_checked) {
            // 更新页面信息
            update_page_info()
        }
    })

    /*购物车商品数量的减少*/
    $(".minus").click(function () {
        // 获取商品的单价和商品的数量
        price = parseFloat($(this).parents("td").prev().text())
        count = parseInt($(this).parent().prev().val())
        // 校验参数
        count = parseInt(count) - 1
        if (count <= 0) {
            return
        }
        // 重新设置商品的数目
        $(this).parent().prev().val(count)
        //重新计算商品小计
        amount = count * price
        $(this).parents("td").next().text(amount.toFixed(2) + "元")
        // 获取商品对应的checkbox的选中状态，如果被选中，更新页面信息
        is_checked = $(this).parents("tr").find(":checkbox").prop("checked")
        if (is_checked) {
            // 更新页面信息
            update_page_info()
        }
    })

    /* 删除购物车中的记录*/
    $("tbody tr").each(function () {
        $(this).children("td:eq(6)").children("a").click(function () {
            // 获取商品所在的tr元素
            tr = $(this).parents("tr")
            // 删除成功，异常页面上商品所在的ul元素
            tr.remove()
            // 获取商品对应的checkbox的选中状态，如果被选中，更新页面信息
            is_checked = $(this).parents("tr").find(":checkbox").prop("checked")
            if (is_checked) {
                // 更新页面信息
                update_page_info()
            }
        })
    })

    /* 购买数量手动修改*/
    $(".count").keydown(function (e) {
        code = e.keyCode
        if (!((code >= 48 && code <= 57) || code == 8 || code == 46)) {
            return false
        }
    })
    $(".count").blur(function (e) {
        // 获取商品的单价和商品的数量
        price = parseFloat($(this).parents("td").prev().text())
        count = parseInt($(this).val())
        //重新计算商品小计
        amount = count * price
        $(this).parents("td").next().text(amount.toFixed(2) + "元")
        // 获取商品对应的checkbox的选中状态，如果被选中，更新页面信息
        is_checked = $(this).parents("tr").find(":checkbox").prop("checked")
        if (is_checked) {
            // 更新页面信息
            update_page_info()
        }
    })


    //更新显示
    update_page_info()
</script>

{% endblock %}

Qshop/Buyer/templates/buyer/edit-address.html
{% extends "buyer/base.html" %}

{% block content%}
    <div class="container">


    <div class="main">
        <div id="allorders" class="col-sm-6 col-sm-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading">修改用户地址</div>
                <div class="panel-body">
                    <form class="form-horizontal">
                        <div class="form-group">
                            <label for="shoujianren" class="col-sm-2 control-label">收件人</label>
                            <div class="col-sm-10">
                                <input type="email" class="form-control" id="shoujianren" placeholder="收件人">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="xiangxiaddress" class="col-sm-2 control-label">详细地址</label>
                            <div class="col-sm-10">
                                    <textarea class="form-control" placeholder="详细地址" id="xiangxiaddress"
                                              rows="3"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="youbian" class="col-sm-2 control-label">邮编</label>
                            <div class="col-sm-10">
                                <input type="email" class="form-control" id="youbian" placeholder="邮政编码">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="youbian" class="col-sm-2 control-label">手机</label>
                            <div class="col-sm-10">
                                <input type="email" class="form-control" id="phone" placeholder="手机号">
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="form-group">
                                <button type="submit" class="btn btn-default col-lg-4 col-lg-offset-4">&nbsp;&nbsp;提&nbsp;交&nbsp;&nbsp;
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
    <br/><br/><br/><br/>
{% endblock %}

Qshop/Buyer/templates/buyer/edit-user.html
{% extends "buyer/base.html" %}

{% block content %}
    <div class="container">
    <div class="main">

        <div id="allorders" class="col-sm-6 col-sm-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading">修改用户信息</div>
                <div class="panel-body">
                    <form class="form-horizontal">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">用户名</label>
                            <div class="col-sm-10">
                                <input type="email" class="form-control" id="inputEmail3" placeholder="用户名">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 control-label">联系方式</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="inputPassword3" placeholder="联系方式">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword4" class="col-sm-2 control-label">联系地址</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="inputPassword4" placeholder="联系地址">
                            </div>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-default col-lg-4 col-lg-offset-4">修&nbsp;&nbsp;改
                            </button>

                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>
    <br/><br/><br/><br/>
{% endblock %}

Qshop/Buyer/templates/buyer/place_order.html
{% extends "buyer/base.html" %}

{% load filters%}

{% block script %}
     <link rel="stylesheet" href="/static/buyer/css/search.css">
{% endblock %}

{% block content %}
    <div class="container">
    <!--2.搜索框开始-->
    <div class="search">
        <div class="row ">
            <div class="col-lg-5">
                <img src="/static/buyer/images/logo.png" alt="..." class="img-rounded">
                <span>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;提交订单</span>
            </div>
            <div class="col-lg-6 col-lg-offset-1 search_bar">
                <form action="">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="搜索商品">
                        <span class="input-group-btn">
                    <button class="btn btn-success" style="padding: 6px 50px" type="submit">搜索</button>
                </span>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!--搜索框结束-->
    <!--3.主体-->
    <div class="main">
        <!--收货地址-->

        <div class="panel panel-default ">
            <div class="panel-heading col-lg-12">确认收货地址</div>
            <div class="panel-body">
                <div>
                    北京市 海淀区 东北旺西路8号中关村软件园 （李思 收） 182****7528
                    <a style="margin-left: 500px" class="btn btn-default" href="edit-address.html"
                       role="button">编辑收货地址</a>
                </div>

            </div>
        </div>
        <!--支付方式-->
        <div class="panel panel-default ">
            <div class="panel-heading col-lg-12">支付方式</div>
            <div class="panel-body">
                <div class="radio">
                    <label>
                        <input type="radio" name="optionsRadios" value="option1" >
                        <img src="/static/buyer/images/pay/yhk.png" alt="..." class="img-thumbnail">
                    </label>
                    <label>
                        <input type="radio" name="optionsRadios" value="option1">
                        <img src="/static/buyer/images/pay/wx.png" alt="..." class="img-thumbnail">
                    </label>
                    <label>
                        <input type="radio" name="optionsRadios" value="option1" checked>
                        <img src="/static/buyer/images/pay/zfb.png" alt="..." class="img-thumbnail">
                    </label>
                    <label>
                        <input type="radio" name="optionsRadios" value="option1">
                        <img src="/static/buyer/images/pay/yl.png" alt="..." class="img-thumbnail">
                    </label>
                </div>

            </div>
        </div>


        <!--商品列表-->
        <div class="panel panel-default ">
            <div class="panel-heading col-lg-12">商品列表</div>
            <div class="panel-body">
                <table class="table table-bordered table-hover">
                    <tr align="center" valign="middle">
                        <td>序号</td>
                        <td>图片</td>
                        <td>商品名称</td>
                        <td>商品单位</td>
                        <td>商品价格</td>
                        <td>数量</td>
                        <td>小计</td>
                    </tr>
                    {% for order_info in porder.orderinfo_set.all %}
                    <tr align="center" valign="center">
                        <td>{{ forloop.counter }}</td>
                        <td>
                            <img class="img-thumbnail" src="/static/{{orderinfo.goods_picture}}" width="60px" alt="">
                        </td>
                        <td>{{ order_info.goods_name }}</td>
                        <td>500g</td>
                        <td>{{ order_info.goods_price }}元</td>
                        <td>{{ orderinfo.goods_num }}</td>
                        <td>{{ orderinfo.goods_total }}</td>
                    </tr>
                    {% endfor %}

                </table>
            </div>
        </div>

        <!--总金额结算-->
        <div class="panel panel-default">
            <div class="panel-heading col-lg-12">总金额结算</div>
            <div class="panel-body">
                <table class="table table-bordered table-hover">
                    <tr align="center" valign="middle">
                        <td>商品件数</td>
                        <td>总金额</td>
                        <td>运费</td>
                        <td>实付款</td>
                    </tr>
                    <tr align="center" valign="center">
                        <td>{{porder.type_number}}</td>
                        <td>
                            {{porder.total_price}}
                        </td>
                        <td>10</td>
                        <td>{{porder.total_price | pay_price}}</td>
                    </tr>

                </table>
            </div>
        </div>

        <!--提交订单按钮-->
        <div>
            <button type="button" class="btn btn-success col-lg-3 col-lg-offset-9">提交订单</button>
        </div>
    </div>

</div>

{% endblock %}